version: '3'

services:
    app:
        image: electron-sticky-notes-image:latest
        container_name: electron-sticky-notes-container
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:8080"
        tty: true