
-- CREATES THE NOTES LIST TABLE

CREATE TABLE IF NOT EXISTS NOTES_LIST (
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	CONTENT TEXT NOT NULL,
	CREATION_DATE DATE NOT NULL
);

-- DATABASE ENTRY TEST

--INSERT INTO NOTES_LIST (CONTENT, CREATION_DATE) VALUES ('TESTING DATABASE', DATE('now'));

-- IF THE DATABASE IS NEW, A DEFAULT ENTRY WILL BE ADDED
-- THIS FILE WILL ONLY RUN IF THE DATABASE DID NOT EXIST PRIORLY

INSERT INTO NOTES_LIST (CONTENT, CREATION_DATE) VALUES ('', DATE('now'));
