
-- CREATES THE NOTES LIST TABLE

CREATE TABLE IF NOT EXISTS NOTES_LIST (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	CONTENT TEXT NOT NULL,
	CREATION_DATE DATE NOT NULL
);

-- DATABASE ENTRY TEST

INSERT INTO NOTES_LIST (CONTENT, CREATION_DATE) VALUES ('TESTING DATABASE', DATE('now'));
